application: icsconvert
version: 17
runtime: python27
api_version: 1
threadsafe: yes

instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 995
  max_pending_latency: 15.0s

handlers:
- url: /css
  static_dir: css

- url: /javascript
  static_dir: javascript

- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: .*
  script: main.app
  secure: always


libraries:
- name: webapp2
  version: "2.5.2"

- name: ssl
  version: latest
